services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ai-agent-tokens
      - JWT_SECRET=your_jwt_secret

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
